### ISSUE TITLE
Nginx doesn't serve application

### ISSUE THREAD

**Issue by Ansiem** [bluemanos/symfony-docker-minimal#1]
Hi friend,

I came across your Symfony Docker Minimal GitHub repository and was trying to
integrate it into my rest_api project. All the services are running but when doing a GET request
to the "/" route I am getting a Nginx configuration screen.

Here is the result I am getting from postman when doing a GET request to "/".
( I have a Controller returning some static data on "/" )

![image](https://user-images.githubusercontent.com/19479222/206907589-38f47be7-467e-4fd8-b60e-eb3e95a8071e.png)

I'm using the exact same:

| - .docker folder
| - .env file (only added some JWT configurations)
| - docker-compose.yml

Hope you can help me out 😄.

**Comment by Ansiem** [comment]
It seems like I fixed it by doing the following: 

Changing line 30 in the docker-compose.yml file from:

`      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/app.conf `

to:

`      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf `

If you have a better solution please let me know.

**Comment by bluemanos** [comment]
@Ansiem I just run the repo localy from scratch and it is working for me - without any additional changes in `docker-compose.yml`, the Symfony Welcome page is showing correctly.

But in my other project I noticed that I have following configuration:
```        volumes:
            - ./:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.dockerfs/var/log/nginx:/var/log/nginx:consistent```
which is consistent with your answer.

**Comment by Ansiem** [comment]
@bluemanos strange. I just did a fresh clone and ran:

1. `composer install`

2. `docker-compose up -d` 

And still get the nginx configuration page.
Only when making the change to the docker-compose file I do get the Symfony Welcome page.

**Comment by bluemanos** [comment]
@Ansiem I just pushed updated `docker-compose.yml` with your suggestion :)
